get:
  operationId: "getDeploymentStrategies"
  summary: Get Deployment Strategies
  description: Gets the available deployment strategies that can be used to orchestrate containers.
  tags:
    - Infrastructure
  parameters: []
  responses:
    200:
      description: Returns available deployment strategies.
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                properties:
                  resource-density:
                    $ref: ../../../components/schemas/infrastructure/DeploymentStrategy.yml
                  high-availability:
                    $ref: ../../../components/schemas/infrastructure/DeploymentStrategy.yml
                  first-available:
                    $ref: ../../../components/schemas/infrastructure/DeploymentStrategy.yml
                  node:
                    $ref: ../../../components/schemas/infrastructure/DeploymentStrategy.yml
                  edge:
                    $ref: ../../../components/schemas/infrastructure/DeploymentStrategy.yml
                  manual:
                    $ref: ../../../components/schemas/infrastructure/DeploymentStrategy.yml
                  function:
                    $ref: ../../../components/schemas/infrastructure/DeploymentStrategy.yml

    default:
      $ref: ../../../components/responses/errors/DefaultError.yml
