title: ScaleThresholdMetricRam
type: object
description: Describes the RAM threshold at which scaling will occur
required:
  - type
  - details
properties:
  type:
    type: string
    enum:
      - ram
  details:
    type: object
    required:
      - used
    properties:
      used:
        $ref: ../../../ByteSize.yml
        description: The limit (maximum) amount of RAM each instance of the given container can use before triggering a scaling event.
