get:
  operationId: "getBillingService"
  tags:
    - Billing
  parameters:
    - name: servicesId
      description: The ID of the billing service.
      in: path
      required: true
      schema:
        type: string
  summary: Fetch Billing Service
  description: Requries the `billing-services-view` capability.
  responses:
    200:
      description: Returns a billing service resources.
      content:
        application/json:
          schema:
            title: "ListBillingServicesResponse"
            type: object
            properties:
              data:
                $ref: ../../../../components/schemas/billing/Service.yml
    default:
      $ref: ../../../../components/responses/errors/DefaultError.yml
