get:
  operationId: "getBillingServices"
  tags:
    - Billing
  parameters:
    - $ref: ../../../../components/parameters/SortParam.yml
    - $ref: ../../../../components/parameters/FilterParam.yml
    - $ref: ../../../../components/parameters/PageParam.yml
  summary: List Billing Services
  description: Requries the `billing-services-view` capability.
  responses:
    200:
      description: Returns a collection of billing service resources.
      content:
        application/json:
          schema:
            title: "ListBillingServicesResponse"
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../../../../components/schemas/billing/Service.yml
    default:
      $ref: ../../../../components/responses/errors/DefaultError.yml
