get:
  operationId: "getBillingService"
  summary: Get Billing Service
  description: Requries the `billing-services-view` capability.
  tags:
    - Billing
  parameters:
    - name: servicesId
      description: The ID of the Billing Service.
      in: path
      required: true
      schema:
        type: string
  responses:
    200:
      description: Returns the Hub's specified Billing Service.
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                $ref: ../../../../components/schemas/billing/Service.yml
    default:
      $ref: ../../../../components/responses/errors/DefaultError.yml
