title: VirtualMachineCpuConfigDefault
type: object
description: Predefined CPU selection.
required:
  - type
  - details
properties:
  type:
    type: string
    enum: [host, qemu32, qemu64, kvm64]
    description: Predefined CPU type.
  details:
    type: object
    description: No additional fields for default CPU types.
    additionalProperties: false
additionalProperties: false
