title: ReconfigureSDNNetwork 
type: object 
required: 
  - action 
  - contents 
properties: 
  action: 
    type: string 
    description: The job to do. 
    enum: 
      - reconfigure 
  contents: 
    type: object 
    description: Additional information needed for the job. 
    required:
      - environment_ids 
    properties: 
      environment_ids: 
        description: An array of environment identifiers for the network. 
        type: array 
        items: 
          type: string 
          