title: IncludedEnvironments
description: |
  A map of environments, keyed by ID, included on endpoints that support it when passing the matching includes query parameter.
type: object
additionalProperties:
  $ref: ../environments/Environment.yml
