title: ContainerConfig
description: A container configuration.
type: object
required:
  - network
  - deploy
properties:
  network:
    $ref: ContainerNetwork.yml
  deploy:
    $ref: ContainerDeploy.yml
  scale:
    $ref: ContainerScale.yml
  runtime:
    $ref: ContainerRuntime.yml
  resources:
    $ref: ContainerResources.yml
  integrations:
    $ref: ContainerIntegrations.yml
