title: ExternalVolumeTask
discriminator:
  propertyName: action
  mapping:
    servers.reconfigure: ExternalVolumeServersReconfigureAction.yml
oneOf:
  - $ref: ExternalVolumeServersReconfigureAction.yml
