title: VpnReconfigureTask
type: object
required:
  - action
  - contents
properties:
  action:
    type: string
    enum:
      - reconfigure
    description: The action to take.
  contents:
    type: object
    description: Additional information the platform needs to create this job.
    properties:
      enable:
        type: boolean
        description: A boolean where true means the VPN service is enabled.
      high_availability:
        nullable: true
        type: boolean
        description: A boolean where `true` represents the desire to run the environment vpn service in high availability mode.
      auto_update:
        nullable: true
        type: boolean
        description: A boolean representing if this service container is set to autoupdate or not
      config:
        type: object
        nullable: true
        description: The config object for the VPN service, in this case without the required fields normally found in a VPN config object.
        properties:
          allow_internet:
            type: boolean
            description: If true, routes all traffic through the VPN, even non-Cycle traffic.
          auth:
            type: object
            description: Auth configuration for the VPN.
            required:
              - webhook
              - cycle_accounts
            properties:
              webhook:
                type: string
                nullable: true
                description:
                  A webhook endpoint to hit. Will be passed the login credentials
                  provided to the user, and should return a 200 status if the login is
                  permitted.
              cycle_accounts:
                type: boolean
                description:
                  If true, allows any Cycle account with access to the environment
                  to log in to the VPN using their Cycle email and password.
              vpn_accounts:
                type: boolean
                description:
                  If true, allows the custom VPN accounts to log in to the
                  VPN.
