title: ReconfigureSharedFs
type: object
required:
  - action
  - contents
properties:
  action:
    type: string
    description: The action to take.
    enum:
      - sharedfs.reconfigure
  contents:
    type: object
    properties:
      mounts:
        type:
          - object
          - "null"
        additionalProperties:
          type: object
          required:
            - type
            - options
            - source
          properties:
            type:
              type: string
              description: String describing the server mount type.
            options:
              type: string
              description: Comma separated string describing the server mount options.
              examples:
                - "key1=value1,key2=value2"
            source:
              type: string
              description: String describing the server mount source.
      directories:
        type:
          - object
          - "null"
        description: An object describing directory identifiers with value {}.
        additionalProperties: {}
