title: ReconfigureServerFeaturesTask
type: object
required:
  - action
  - contents
properties:
  action:
    type: string
    description: The action to take.
    enum:
      - features.reconfigure
  contents:
    type: object
    description: Supplemental information needed to perform the action.
    properties:
      sftp:
        type: boolean
        description: A boolean where true represents the desire for the server to accept incoming SFTP requests for container volumes.
      base_volume_gb:
        type:
          - integer
          - "null"
        description: A number in GB for how big the base volume should be.  This cannot be lower than the currently set value for the server.
      gateway:
        type:
          - object
          - "null"
        description: Configuration options for running gateway services on this server.
        properties:
          type:
            type: string
            description: The type of gateway service that can be run on this server.
            enum:
              - bgp
              - static
        required:
          - type
