title: VirtualMachineIpAllocateTask
type: object
required:
  - action
  - contents
properties:
  action:
    type: string
    enum:
      - ip.allocate
    description: The action to take.
  contents:
    type: object
    properties:
      ip_id:
        $ref: ../../ID.yml
        description: The ID of the IP address to allocate to the virtual machine.
