---
get:
  operationId: getEnvironmentDeployments
  tags:
    - Environments
  parameters:
    - name: environmentId
      description: The ID of the environment to get the list of deployments for.
      in: path
      required: true
      schema:
        type: string
  summary: List Environment Deployments
  description: |
    Gets a list of all deployments in the specified environment.

    Requires the `environments-view` capability.
  responses:
    200:
      description: A list of deployments.
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                description: A map where the key is the version property of a deployment.
                additionalProperties:
                  type: object
                  required:
                    - containers
                  properties:
                    containers:
                      type: integer
                      description: The number of containers utilizing this version of this deployment.
    default:
      $ref: ../../../components/responses/errors/DefaultError.yml
